name: SBX CICD AWS Lambda Layer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: sandbox

    steps:
      - name: "Checks-out GitHub Repository"
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: "Verify changed files"
        uses: tj-actions/changed-files@v23.1
        id: changed-files
        with:
          files: |
            mv/*/*/build.sql
            v/*/*/build.sql

      - name: "List all changed files and deploy"
        run: |
          files=()
          echo All modified files: "${{ steps.changed-files.outputs.all_modified_files }}"

          delimiter="/"
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo $file
            declare -a array=($(echo $file | tr "$delimiter" " "))
            type=${array[0]}
            dataset=${array[1]}
            table=${array[2]}
            filename=${array[3]}

            if [ $type="mv" ]
            then
              echo type=$type
              echo dataset=$dataset
              echo table=$table
              echo filename=$filename
            fi
            
          done

  build-and-deploy_2:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    env:
      ENVIRONMENT: sandbox

    steps:
      - name: "Checks-out GitHub Repository"
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
