name: SBX CICD AWS Lambda Layer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: sandbox

    steps:
      - name: "Checks-out GitHub Repository"
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: "Verify changed files"
        uses: tj-actions/changed-files@v9
        id: changed-files
        with:
          files: |
            [sql]*

      - name: "List all changed files and deploy"
        run: |
          files=()
          echo All modified files: "${{ steps.changed-files.outputs.all_modified_files }}"

          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            files+="${file}"" "

          for file in $files; do
            python main.py $file
          done
